name: Collect PUBG Stats

on:
  schedule:
    # 매일 한국시간 오전 9시 (UTC 00:00)에 실행
    - cron: '30 0 * * *'
  workflow_dispatch: # 수동 실행도 가능하도록

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Git push 권한 추가
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd scripts
        npm install
    
    - name: Collect and save stats
      env:
        PUBG_API_KEY: ${{ secrets.PUBG_API_KEY }}
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        cd scripts
        node collect-daily-stats.js
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily stats [skip ci]" && git push origin main)
