name: Update PUBG Stats

on:
  schedule:
    # 매시간 실행 (:00분에)
    - cron: '0 * * * *'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm install firebase-admin node-fetch@2
    
    - name: Create service account file
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
    
    - name: Run stats update
      run: node update-stats.js
      env:
        NODE_ENV: production
    
    - name: Clean up
      if: always()
      run: rm -f firebase-service-account.json
    
    - name: Notify success
      if: success()
      run: echo "✅ Stats update completed successfully at $(date)"
    
    - name: Notify failure
      if: failure()
      run: echo "❌ Stats update failed at $(date)"
