# This workflow has been replaced by collect-stats.yml
# Disabled to prevent errors
name: Update PUBG Stats (DISABLED)

on:
  workflow_dispatch:  # 수동 실행만 가능 (자동 실행 비활성화)

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - name: Workflow Disabled
      run: |
        echo "❌ This workflow has been disabled."
        echo "Please use 'Collect PUBG Stats' workflow instead."
        echo "To run stats collection, go to Actions tab and run 'Collect PUBG Stats' workflow."
        exit 1